hijri.config:
  type: config_object
  label: 'Hijri settings'
  mapping:
    correction_value:
      type: integer
      label: 'Correction days'
    hijri_types:
      type: mapping
      label: 'Hijri date Correction field for specific content types'
      mapping:
        default:
          type: string
          label: 'Default'
    hijri_display:
      type: mapping
      label: 'Hijri date On Nodes'
      mapping:
        default:
          type: string
          label: 'Default'
    hijri_comment_display:
      type: mapping
      label: 'Hijri date On Comments'
      mapping:
        default:
          type: string
          label: 'Default'
    hijri_display_block:
      type: mapping
      label: 'Hijri date On Module Block'
      mapping:
        default:
          type: string
          label: 'Default'
